name: ts

# Run this workflow every time a new commit pushed to your repository
on:
  push:
  pull_request:
  schedule: [cron: "40 1 * * *"]

jobs:
  vsce:
    name: visual studio extension package
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update && sudo apt install -y nodejs npm
      - run: |
          npm install 
          sudo npm install -g vsce
          echo y|vsce package

      - name: releasefile
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            LICENSE
            vscode-*.vsix
            
